Handle cases where no rate limiting is used
janeklb/gh-search pull request #62
Opened 2023-10-19 23:40 UTC by augustd

In this case I catch the exception that is thrown and create a rate limit object with significantly high (1 billion) remaining requests. The rest of the code operates normally.

2023-10-19 23:41 UTC, augustd commented
Fixes #61

2023-10-20 01:11 UTC, augustd commented
A nice addition to this would be to suppress/ignore/auto answer 'yes' to the `Do you want to continue? [y/N]:` message.

2024-08-03 19:40 UTC, janeklb requested changes
Hi @augustd - thank you for the contributions (just noticed them now!)

2024-08-03 19:40 UTC, janeklb commented on ghsearch/gh_search.py
> +            # Handle the exception by returning a default rate limit dictionary
Can the exception type be scoped down to something more specific?

2024-08-03 19:40 UTC, janeklb commented on ghsearch/gh_search.py
> +            # Handle the exception by returning a default rate limit dictionary
(i've updated the PyGithub dependency -- i suggest rebasing your PR branch from main to see what the latest version does)

2024-08-03 22:30 UTC, janeklb approved these changes

2024-08-03 22:32 UTC, janeklb commented
@augustd are you able to verify that the changes I've made work for you?

2024-08-10 14:29 UTC, merged